name: React - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      working-directory: ${{env.working-directory}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: npm install

    - name: Run the tests
      working-directory: ${{env.working-directory}}
      run: npm test -- --coverage

    - name: Analyze Code Coverage
      working-directory: ${{env.working-directory}}
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      
    - name: Build
      working-directory: ${{env.working-directory}}
      run: npm run build
