name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
        # Outputs: "Running on pr: feature/test".

      #- name: Commit any changed files
      #run: echo ${GITHUB_REF#refs/heads/}
      #uses: mikeal/publish-to-github-action@master
      #env:
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
