name: Lint
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_command: ["npm lint --quiet", "npm tc", "npm prettier --check"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          always-auth: true
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Setup
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - run: ${{ matrix.test_command }}
